name: CI + CD

on:    
  workflow_dispatch:
    inputs:
      terraform:
        description: Create infrastructure
        type: boolean
        required: false
        default: false      
      theme_test:
        description: Test theme
        type: boolean
        required: false
        default: false
      pull_request_development:
        description: Create pull request to development
        type: boolean
        required: false
        default: false     
      pull_request_production:
        description: Create pull request to production
        type: boolean
        required: false
        default: false    
      version_type:
        type: choice
        description: Define the version type
        default: ""
        options:
        - patch 
        - minor
        - major       
      ip_address:
        description: IP de acesso ao servidor
        type: string
        required: false
        default: ""                  

jobs:
  terraform:
    name: Create infrastructure
    if: ${{ inputs.terraform }}
    uses: ./.github/workflows/terraform.yml  
    secrets:
      TF_DIGITALOCEAN_PUB: ${{ secrets.TF_DIGITALOCEAN_PUB }}
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
      
  theme_test:
    name: Test application
    if: ${{ inputs.theme_test }}
    uses: ./.github/workflows/theme_review_action.yml

  pull_request_development:
    name: Open pull request to development
    if: ${{ inputs.pull_request_development }}
    needs: [theme_test]    
    uses: ./.github/workflows/pull_request.yml  

  type_version:
    name: Open pull request to production
    if: ${{ inputs.pull_request_production }}
    uses: ./.github/workflows/type_version.yml  
     
  pull_request_production:
    name: Open pull request to production
    if: ${{ inputs.pull_request_production }} 
    needs: [type_version]
    uses: ./.github/workflows/pull_request.yml          

  deploy_production:
    name: Deploy to production
    if: ${{ inputs.pull_request_production }} 
    needs: [pull_request_production]
    uses: ./.github/workflows/deploy_theme.yml       