name: Install theme on production

on:
  workflow_call:
  pull_request:
    branches:
      - 'production'      
    types:
      - closed            

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    timeout-minutes: 15
    steps:    
      - name: executing remote ssh commands using private key   
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ inputs.ip_address }}
          script: |
            echo "Deploying theme to server"
            git clone git@github.com:danieljesussp/deploy-theme-wordpress.git   
            chown -R www-data:www-data deploy-theme-wordpress
            mv /var/www/html/wp-content/themes/deploy-theme-wordpress /var/www/html/wp-content/themes/deploy-theme-wordpress.bak             
            rsync -av deploy-theme-wordpress /var/www/html/wp-content/themes            
            rm -fr /var/www/html/wp-content/themes/deploy-theme-wordpress.bak
            rm -rf deploy-theme-wordpress
            echo "Deploying theme to server completed"       