name: Theme test

on:
  workflow_call:
  pull_request:
    branches:
      - '!development'            
    types:
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest 
    timeout-minutes: 10        
    steps:
        - name: "☁️ checkout repository"
          run: echo "Hello World"